### ISSUE TITLE
Not working on Linux.. !!!

### ISSUE THREAD

**Issue by ricardojlrufino** [MarkusSprunck/yaca-monitor#1]
Unable to run on linux .. 
First I created the  start script ... 

Run output...:
Mai 28, 2014 7:51:15 PM com.sw_engineering_candies.yaca.CallStackAnalyser findOtherAttachableJavaVMs
Grave: Unable to open socket file: target process not responding or HotSpot VM not loaded

In firefox was showing some errors in the console URL, then changed the: yaca.main.js and solved some errors. 
But the request is sent and has no answer. 

yaca.main.js
```
function updateTimerImport() {
	"use strict";
	if (YACA_SimulationOptions.RUN_IMPORT) {
		importAgentData("http://localhost:3333/processes/" + YACA_SimulationOptions.ACTIVE_PID);
	}
}
```

Start.sh
```
#!/bin/sh
echo YACA-AGENT - STATIC AND DYNAMIC ANALYSIS
echo ========================================

export JAVA_HOME=/media/Dados/Programacao/jdk1.7.0_55
export PATH=$PATH:$JAVA_HOME/bin

echo Start YacaAgentTestClient...
java -Xint -jar YacaAgentTestClient.jar &
java -Xint -jar YacaAgentTestClient.jar &

echo Start YacaAgent...
export CLASSPATH=$CLASSPATH:$JAVA_HOME/lib/tools.jar:YacaAgent.jar
java com.sw_engineering_candies.yaca.Agent

```

**Comment by MarkusSprunck** [comment]
The new release candidate is developed and tested under OS X (see https://github.com/MarkusSprunck/yaca-monitor/releases).  

Implementation based on:
- Eclipse 4.4.2 (Luna Service Release 2)
- Java JDK 1.8.0_77
- Tested target systems: Windows 7 and OS X
- ECMAScript Edition 6 (ES6) based on traceur.js
- THREE.WebGLRenderer 75

News:
- Yaca-Agent serves as webserver for the Yaca-Monitor (WebGL Frontend)
- direct interaction with Yaca-Agent (reset model, black/white lists, etc.)
- improved performance
- support for OS X
- black and white lists
