### ISSUE TITLE
JS Support

### ISSUE THREAD

**Issue by Spencerx** [MarkusSprunck/yaca-monitor#2]
Can we visualise JS/HTML5 code at some point. Say visualise a Git repo against a working JS/HTML5 application.

**Comment by MarkusSprunck** [comment]
In principal this would be possible, but the Yaca-Agent is focused on Java call stack analysis.

**Comment by Spencerx** [comment]
It's possible, we can have a headless java engine working online or on premise using the cloud for remote render it is worthwhile when you have the likes of the nvidia DGX-1

**Comment by Spencerx** [comment]
I'm sure you have not come across a use case I have a few in mind using @Rhino https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino
